### PR TITLE
Dark Mode!?

### PR DESCRIPTION
**Pull request by rayriffy**
~~Yes, we are adding `preact` into **Riffy Blog** which could speed up Riffy Blog by >30KB smaller~~

Preact will be open as a new branch due to `dangerouslySetInnerHTML` is buggy on client-side

### CODE REVIEW

**Comment by aomkirby123** [comment]
Preact beta.3 is out for a while now with some changes. I recommended testing on beta.3 as it would be based on beta.3 with it’s stable.
It’s recommended to test it out too, since beta.3 has some problem with some React framework and library (eg. Next.js, react-render-to-string). Also beta.3 change the way Fragment’s core is and some TypeScript bug fixed.
But I think beta.3 would have no problem with Gatsby v2, but just to make sure.

**Comment by rayriffy** [comment]
So, I need to install `preact@next` instead of `preact@beta`? I can try that.

**Comment by rayriffy** [comment]
@aomkirby123 `dangerouslySetInnerHTML` still not being rendered https://deploy-preview-673--rayriffy-blog-staging.netlify.com/review-code-mania-1001/

**Comment by rayriffy** [comment]
I think it's a good time for now to deploy only Dark Mode. ┐('～`;)┌

**Comment by rayriffy** [comment]
All development that include `preact` will be moved to https://github.com/rayriffy/rayriffy-blog/pull/674

**Pull request merged**
